services:
  server:
    build:
      context: .
    environment:
      - RUST_LOG=debug
    volumes:
      - ../target/release/examples:/app
    stop_grace_period: 1s
    command: /app/eval_fa2_pubsub_server
    networks:
      - development
    
  client:
    build:
      context: .
    environment:
      - RUST_LOG=debug
    volumes:
      - ../target/release/examples:/app
    stop_grace_period: 1s
    command: /app/eval_fa2_pubsub_client
    networks:
      - development
    depends_on:
      - server

networks:
  development:
    name: development
