# docker compose -f docker-compose.nfa5.yml up
services:
  server:
    build:
      context: .
    environment:
      - RUST_LOG=info
    volumes:
      - ../target/release/examples:/app
    command: /app/eval_nfa5_scalability_server
    networks:
      - development

  client:
    build:
      context: .
    environment:
      - RUST_LOG=info
    volumes:
      - ../target/release/examples:/app
    command: /app/eval_nfa5_scalability_client
    depends_on:
      - server
    networks:
      - development
    deploy:
      replicas: 8

  tcpdump:
    image: kaazing/tcpdump
    networks:
      - development
    volumes:
      - ./tcpdump:/tcpdump

networks:
  development:
    name: development
