services:
  server:
    image: ubuntu:22.04
    environment:
      - RUST_LOG=debug
    volumes:
      - ./target/release/examples:/app
    command: /app/_dev_server
    networks:
      - development
    
  client:
    image: ubuntu:22.04
    environment:
      - RUST_LOG=debug
    volumes:
      - ./target/release/examples:/app
    command: /app/_dev_client
    networks:
      - development

networks:
  development:
    name: development
