services:
  provider:
    image: ubuntu:22.04
    volumes:
      - ./target/debug/examples:/app/examples
    command: /app/examples/sd 1 5
    networks:
      - development
    
  discover:
    image: ubuntu:22.04
    volumes:
      - ./target/debug/examples:/app/examples
    command: /app/examples/sd 2 2
    networks:
      - development
    depends_on:
      - provider

networks:
  development:
    name: development