services:
  server:
    build:
      args:
        TARGET: _dev_server
    environment:
      - RUST_LOG=debug
    stop_grace_period: 1s
    networks:
      - development
    
  client:
    build:
      args:
        TARGET: _dev_client
    environment:
      - RUST_LOG=debug
    stop_grace_period: 1s
    networks:
      - development
    depends_on:
      - server

networks:
  development:
    name: development
