services:
  server:
    image: debian:bookworm-slim
    environment:
      - RUST_LOG=debug
    stop_grace_period: 1s
    volumes:
      - ../:/app
    command: sh -c "/app/target/debug/examples/_dev_server"
    networks:
      - development
    
  client:
    image: debian:bookworm-slim
    environment:
      - RUST_LOG=debug
    stop_grace_period: 1s
    volumes:
      - ../:/app
    command: sh -c "/app/target/debug/examples/_dev_client"
    networks:
      - development
    depends_on:
      - server

networks:
  development:
    name: development